### ISSUE TITLE
Subfield repeater gets an extra row at the beginning

### ISSUE THREAD

**Issue by rokpremrl** [mcguffin/acf-duplicate-repeater#10]
Hi,

There is a bug when you are duplicating a row that contains another repeater. That sub-level repeater gets an extra row at the first place (before other rows of sub-level repeater). I hope my description is clear enough.

BR,
Rok

**Comment by mcguffin** [comment]
Hi Rok,
Thanks for the report and welcome to my github repo.
I just tested it with nested a repeater fields, but everything seemed to work fine. Would you mind to post a json dump of your ACF Field, so I can test for your specific use case? 
Knowing which other (ACF-Related) plugins are running might be helpful too, in case its a compatibility issue.
Best regards
Jörn

**Comment by erik91** [comment]
Having the same trouble.
http://prntscr.com/m6lswi
http://prntscr.com/m6lt3j

**Comment by mcguffin** [comment]
@erik91: could you post your ACF field group json export here, so I can test?

**Comment by erik91** [comment]
I do have php export only :/
`
        'dates_block' => array(
            'key' => 'dates_block',
            'name' => 'dates',
            'label' => 'Dates',
            'display' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'dates_block_dates',
                    'label' => 'Dates',
                    'name' => 'dates',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 1,
                    'max' => 0,
                    'layout' => 'block',
                    'button_label' => '',
                    'sub_fields' => array(
                        array(
                            'key' => 'dates_block_dates_date',
                            'label' => 'Date',
                            'name' => 'date',
                            'type' => 'date_time_picker',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'display_format' => 'Y-m-d H:i:s',
                            'return_format' => 'Y-m-d H:i:s',
                            'first_day' => 1,
                        ),
                        array(
                            'key' => 'dates_block_dates_cast',
                            'label' => 'Cast',
                            'name' => 'casts',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 1,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'dates_block_dates_cast_cast',
                                    'label' => 'Cast',
                                    'name' => 'cast',
                                    'type' => 'post_object',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'post_type' => array(
                                        0 => 'authors',
                                    ),
                                    'taxonomy' => '',
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'return_format' => 'object',
                                    'ui' => 1,
                                ),
                                array(
                                    'key' => 'dates_block_dates_cast_cast_role',
                                    'label' => 'Role',
                                    'name' => 'role',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                        ),
                        array(
                            'key' => 'dates_block_dates_location',
                            'label' => 'Location',
                            'name' => 'location',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'LNOBT - Didžioji salė',
//                            'default_value' => '',
//                            'default_value' => __('LNOBT - Didžioji salė', 'opera'),
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'dates_block_dates_link',
                            'label' => 'Link',
                            'name' => 'link',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'dates_block_dates_button',
                            'label' => 'Button',
                            'name' => 'button',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                    ),
                ),
            ),
            'min' => '',
            'max' => '1',
        ),`

**Comment by erik91** [comment]
@mcguffin thanks, i will test it and let you know asap.

**Comment by erik91** [comment]
@mcguffin looks like issue has been solved. thanks alot!

**Comment by mcguffin** [comment]
Very Good! I just popped out a new release including the fix (1.2.11).
Thanks again for the report and for your cooperation :)
