### ISSUE TITLE
Tag release semantic

### ISSUE THREAD

**Issue by MaximeCulea** [mcguffin/acf-duplicate-repeater#14]
Hi there 👋
You should really consider using [Semver](https://semver.org) semantic versioning system : <b>x.y.z</b>
Thank you

**Comment by mcguffin** [comment]
Is it just the `v` prefix that is bothering you? Why would it be important to have it removed?

**Comment by mcguffin** [comment]
Okay, I see the problem...
I not very familiar with composer. Does it check out a release tag or download zip or is it just pulling from the master or whatever branch? If releases: there is the release name and the tag name, both of which have the `v` prefix. Which one do you think, should be the samantic one? Maybe both?

**Comment by mcguffin** [comment]
@MaximeCulea Release names are now have sematic names. Tags names are still prefixed with v, as recommended by github. Can we close this?

**Comment by MaximeCulea** [comment]
Hi @mcguffin, it's better but still not Semver version.
I dl by the end the last realase and not used it with composer.
