### ISSUE TITLE
1.2.9 Causing HTTP 500 error on /wp-admin/plugins.php

### ISSUE THREAD

**Issue by pmascis** [mcguffin/acf-duplicate-repeater#15]
As topic states, 1.2.9 just causes my plugins page to http 500 error.
Has done this for me on a few WordPress installs,
The error doesn't occur with me in 1.2.7.

**Comment by atomiccherry** [comment]
Same issue here.

**Comment by mcguffin** [comment]
should be fixed in 1.2.10.
