### ISSUE TITLE
Not cloning repeaters within repeater or WYSIWYG

### ISSUE THREAD

**Issue by theodejager** [mcguffin/acf-duplicate-repeater#17]
In a repeater field with 2 tabs and accordions (containing repeater fields and WYSWYG editors themselves) only the values of the first accordion on the first tab are copied (this used to work in the past, so it might have to do with ACF / WP compatibility)

**Comment by mcguffin** [comment]
Okay I see!
It might be fixed and avaialble in the next release – hopefully on wordpress.org then.

**Comment by theodejager** [comment]
Thanks for the fix!
