### ISSUE TITLE
Not duplicating all fields values for a Flexible Content field with nested flexible content fields.

### ISSUE THREAD

**Issue by jberg1** [mcguffin/acf-duplicate-repeater#18]
This is a plugin/extension I have been hoping for, to expand my page builder using Flexible Content Fields.

I'm just having an issue when I duplicate a Flexible Content field with other nested flexible content fields, that it fails to duplicate all the values for specific field types in the parent and grandparent layouts, but does work fine for all the child flexible content layouts. 

Mainly with:
Image File, Number fields, Color Pickers, Select field, and Radio Buttons (from my testing).
The duplicated layout (parent/grandparent), the fields just reset to default or null for the duplicated layout.

My example is:
I have a flexible content field (row) with various fields in the layout including another flexible content field (column). Within the column flexible content layout I then have various fields and a third flexible content field (content) with multiple layouts. When I duplicate the section or column, it duplicates all the content layouts correctly, but not the values for the other fields within the section & column layouts (other than text fields). The above mentioned field types just fall back to null or default.  When I duplicate a child layout on it's own, it works fine too.

Row Layout ->Column Layout->Content Layouts
Am I pushing the limit, :) Asking too much? 
Thanks for any help you can provide.

**Comment by mcguffin** [comment]
Interesting :) 
Theroretically there should be no limits, so thanks for the wonderful edge case!
I made some major changes during the last few weeks and just submitted the plugin to wporg. I also added a test scenario with three nested layout fields (https://github.com/mcguffin/acf-duplicate-repeater/blob/master/test/acf-json/group_acf_duplicate_repeater_layout_nested.json), that might be similar to yours.
You might either like to wait a few days until the plugin appears in the plugin repository or – for the impatient – give it another test with the current master branch.

If you still run into errors, please post your field group JSON here, and I'll take another look.

**Comment by jberg1** [comment]
Thanks mcguffin.
I see where my issue was focused.  I have my additional fields for row and column in an accordion field (so they can be collapsed and kept out of the way). When duplicating, those fields were going blank or default (except text fields). When they are not in an accordion they do get duplicated correctly.

Looks like you resolved this in your recent update (fixed accordion #17). It works fine now.
You are king! Cheers!!!
