### ISSUE TITLE
Duplicate -copy Button Created

### ISSUE THREAD

**Issue by mbryne** [mcguffin/acf-duplicate-repeater#19]
Greetings,

Thanks for the excellent plugin,

I am using ACF 5.8.2 and positioning my icons so they are always visible to the user on the front end form. 

As a result of this I've noticed the icon appears multiple times. I think it is getting duplicated as a result of it already being present in the row? I have tested this in the admin with no changes to CSS and it appears multiple times in those rows as well.

Let me know if you need more information.

<img width="790" alt="Screen Shot 2019-08-29 at 1 11 50 pm" src="https://user-images.githubusercontent.com/1341844/63907420-b0980480-ca5e-11e9-8442-a0c4ab4d9f27.png">

**Comment by mcguffin** [comment]
Greetings tto
Thanks for the excellent report!
In the rendering function I just missed to check if the icon already exist.
A fix will be available soon.

**Comment by mbryne** [comment]
Thanks @mcguffin!
