### ISSUE TITLE
incompatibility

### ISSUE THREAD

**Issue by newtlabs** [mcguffin/acf-duplicate-repeater#21]
There is an incompatibility with the latest version of WP and/or ACF Pro.

An error of type E_ERROR was caused in line 45 of the file /wp-content/plugins/acf-duplicate-repeater/index.php. Error message: Uncaught Error: Class 'ACFDuplicateRepeater\Core\Core' not found in /wp-content/plugins/acf-duplicate-repeater/index.php:45

**Comment by mcguffin** [comment]
Hmm ... this doesn't happen in my setup. (WP 5.3 and ACF 5.8.7)
Some questions, before I go into further investigation:
Are you using the latest plugin version from the WP Plugin repository (2.0.2)?
Did you try to re-install the plugin?
Does the file `include/ACFDuplicateRepeater/Core/Core.php` exist in the plugin's directory?
Which PHP version are you using?

**Comment by mcguffin** [comment]
closed due to inactivity
